# Generated by Django 2.1.3 on 2018-11-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pyb_date',
            new_name='pub_date',
        ),
    ]
